---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: pid003
    hostname: pid003
    image: registry.access.redhat.com/ubi8/ubi-init:latest
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    ssh_connection:
      pipelining: false
verifier:
  name: ansible
