---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

provisioner:
  name: ansible
  config_options:
    defaults:
      collections_path: ${ANSIBLE_COLLECTIONS_PATH}

platforms:
  - name: ubi8
    image: registry.access.redhat.com/ubi8/ubi-init:latest
    command: /sbin/init

driver:
  options:
    managed: False
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman
